version: '3'
services:
  app:
    build:
      args:
        - CURATION_APP_PATH=${CURATION_APP_PATH}
      context: .
      dockerfile: Dockerfile
    tty: true
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      - './workspace:${CURATION_APP_PATH}'
      - './.env:${CURATION_APP_PATH}/.env'
    environment:
      - TZ=${SERVER_TIMEZONE}
  meilisearch:
    image: getmeili/meilisearch:latest
    ports:
      - '7700:7700'
    volumes:
      - './data:${MEILI_DB_PATH}'
    environment:
      - TZ=${SERVER_TIMEZONE}
      - MEILI_HTTP_ADDR
      - MEILI_MASTER_KEY
      - MEILI_DB_PATH
